### PR TITLE
Added cross platform picture sharing, group name in received message

### PR DESCRIPTION
**Pull request by icecube45**
Also removed the config.json and replaced it with a username and password in the bot constructor. In order for cross platform picture sharing to work, replace the "BOT DIRECTORY GOES HERE", with the directory that holds the bot code.

### CODE REVIEW

**Comment by Liryna** [comment]
OH ! I will review this when I can :heart:  !!

Is it normal that you changed the link here ? After accepting the pull request this gonna be fixed automatically.
https://github.com/icecube45/FacebookBot/commit/e9ada4d39e09743265dbb84d73518efad7e92e26#diff-04c6e90faac2675aa89e2176d2eec7d8L4

**Comment by icecube45** [comment]
Oop, I did that for my own testing, let me update that back.

**Comment by Liryna** [comment]
Thank you ! This seems to work great but we also get the name of the group when it is a private talk :(
Do you think you could fix it ?

Great work and thanks for updating the dependency !

**Comment by icecube45** [comment]
You mean if it is a one on one conversation, you will get "Name: Name: hello" ?
If so, I can give it a shot, no guarantees

**Comment by Liryna** [comment]
Yes thats right.
If I remember you can get list of people of the conversation (not sure)

**Comment by icecube45** [comment]
That's what I'm checking...

It appears telegram's bot api might be a bit broken right now? I keep getting an error when the bot tries to send a message (via both the wrapper and the web call).

**Comment by Liryna** [comment]
Telegram seems to be alright for me

**Comment by icecube45** [comment]
Hmm, that concerns me, I'll investigate more.

**Comment by icecube45** [comment]
Telegram api is working again, fixed the group message thing.

**Comment by Liryna** [comment]
Thank you @icecube45 great work :) !

**Pull request merged**
